name: binder-env
channels:
  - conda-forge
dependencies:
  - python==3.7
  - pandas
  - numpy
  - matplotlib
  - scipy
  - hvplot
  - geoviews
  - holoviews
  - xarray
  - ipywidgets
  - widgetsnbextension
  - dask
  - zarr
  - pip:
      - watermark
